# Generated by Django 2.2.1 on 2019-07-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='galleryy',
        ),
    ]
