# Generated by Django 2.2.1 on 2019-07-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190716_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('designation', models.CharField(max_length=140)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField()),
            ],
        ),
    ]
