# Generated by Django 2.2.1 on 2019-07-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_food_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='menuu',
        ),
    ]
