# Generated by Django 2.2.1 on 2019-07-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190717_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('info', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('cat', models.ForeignKey(on_delete=False, to='app.photo')),
            ],
        ),
    ]
