# Generated by Django 2.2.1 on 2019-07-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190719_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='nameq',
        ),
    ]
